services:
  app:
    build:
      context: ./src/WebShark
      dockerfile: Dockerfile
    container_name: webshark-app
    restart: unless-stopped
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    working_dir: /var/www
    volumes:
      - ./src/WebShark:/var/www
    env_file:
      - ./src/WebShark/.env
    networks:
      - webshark-net

  nginx:
    image: nginx:alpine
    container_name: webshark-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src/WebShark:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webshark-net

  db:
    image: postgres:15-alpine
    container_name: webshark-db
    restart: unless-stopped
    env_file:
      - ./src/WebShark/.env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webshark-net

  redis:
    image: redis:alpine
    container_name: webshark-redis
    networks:
      - webshark-net

  node:
      build:
        context: ./src/WebShark
        dockerfile: node.Dockerfile
      container_name: webshark-node
      user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
      working_dir: /var/www
      env_file:
        - ./src/WebShark/.env
      volumes:
        - ./src/WebShark:/var/www
      ports:
        - "5173:5173"
      command: npm run dev
      networks:
        - webshark-net

networks:
  webshark-net:
    driver: bridge

volumes:
  postgres-data: