services:
  app:
    build:
      context: ./src/WebShark
      dockerfile: Dockerfile
    container_name: webshark-app
    restart: unless-stopped
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    working_dir: /var/www
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
    volumes:
      - ./src/WebShark:/var/www
    env_file:
      - ./src/WebShark/.env
    networks:
      - webshark-net

  # Uses Supercronic
  cron:
    build:
      context: ./src/WebShark
      dockerfile: Dockerfile
    container_name: webshark-cron
    restart: unless-stopped
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    working_dir: /var/www
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
    volumes:
      - ./src/WebShark:/var/www
    env_file:
      - ./src/WebShark/.env
    command: ["supercronic", "/etc/crontab"]
    networks:
      - webshark-net

  # The Queue Worker (Processes the PCAP jobs in background)
  queue-worker:
    build:
      context: ./src/WebShark
      dockerfile: Dockerfile
    restart: unless-stopped
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    working_dir: /var/www
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
      app:
        condition: service_started
    volumes:
      - ./src/WebShark:/var/www
    env_file:
      - ./src/WebShark/.env
    command: php artisan queue:work --tries=3 --timeout=600 --memory=1024
    networks:
      - webshark-net

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: webshark-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src/WebShark:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webshark-net

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: webshark-db
    restart: unless-stopped
    env_file:
      - ./src/WebShark/.env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - webshark-net

  # Valkey Queue
  valkey:
    image: valkey/valkey:9.0.3-alpine
    container_name: webshark-valkey
    restart: unless-stopped
    networks:
      - webshark-net

  # Node.js (Vite/Vue)
  node:
    build:
      context: ./src/WebShark
      dockerfile: node.Dockerfile
    container_name: webshark-node
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    working_dir: /var/www
    env_file:
      - ./src/WebShark/.env
    volumes:
      - ./src/WebShark:/var/www
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - webshark-net

networks:
  webshark-net:
    driver: bridge

volumes:
  postgres-data: